# -*- coding: utf-8 -*-
"""Doordash Pandas - Exercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxeBi1Z63fhzhb_ZGD4-IArI3vfl61iF
"""

import pandas as pd 
import numpy as np 

url = 'https://raw.githubusercontent.com/JuanPabloSolano1/Doordash/master/MASTER%20DATA%20%20-%20Sheet1.csv?token=Abk7ljU3th9ISeatoq1vXGhznSiOuK7-ks5cnp6RwA%3D%3D'
      
analysis = pd.read_csv(url)
print(analysis.head(5))


print(analysis.columns)
print(analysis.describe())

revise_city = analysis.groupby('Location').size().sort_values(ascending = False)
print(revise_city)

driver_analysis = analysis.groupby('Driver ID').size().sort_values(ascending = False)
print(driver_analysis)

revenue = analysis['Order total'].sum()
print(round(revenue))

order = analysis['Order total']

check_revenue = analysis.groupby(['Location']).sum()
print(check_revenue['Order total'].sort_values(ascending = False))
print(check_revenue['Amount of discount'].sort_values(ascending = False))
print(check_revenue['Refunded amount'].sort_values(ascending = False))

check_palo = analysis.loc[analysis['Location'] == 'Palo Alto']
palo_alto_revenue = (check_palo['Order total'].sum())

percentage_palo_alto = (palo_alto_revenue / revenue) * 100
print(round(percentage_palo_alto))


check_mountain_view = analysis.loc[analysis['Location'] == 'Mountain View']
mountain_view_revenue = (check_mountain_view['Order total'].sum())
percentage_mountain_view = (mountain_view_revenue / revenue) * 100
print(round(percentage_mountain_view))


check_san_jose = analysis.loc[analysis['Location'] == 'San Jose']
san_jose_revenue = (check_san_jose['Order total'].sum())
percentage_san_jose = (san_jose_revenue / revenue) * 100
print(round(percentage_san_jose))